version: "3.8"

services:
  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock-mock-api
    ports:
      - "8080:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
      - ./__files:/home/wiremock/__files
    command: --verbose
